$(function(){$("#datepicker, #datepicker2, #datepicker3").datepicker({minDate:-0,maxDate:"+3M +10D",changeMonth:!0,changeYear:!0,showButtonPanel:!0,selectOtherMonths:!0,showOtherMonths:!0})});
$(function(){var a=$("#from, #to").datepicker({changeMonth:!0,changeYear:!0,selectOtherMonths:!0,showOtherMonths:!0,showButtonPanel:!0,minDate:-0,onSelect:function(b){var c="from"===this.id?"minDate":"maxDate",d=$(this).data("datepicker");b=$.datepicker.parseDate(d.settings.dateFormat||$.datepicker._defaults.dateFormat,b,d.settings);a.not(this).datepicker("option",c,b)}})});
$(function(){$("#calendarAsso").datepicker({minDate:-0,maxDate:"+3M +10D",changeMonth:!0,showButtonPanel:!0,selectOtherMonths:!0,showOtherMonths:!0})});
$(function(){$("#fromN").datepicker({defaultDate:"+1w",minDate:-0,changeMonth:!0,numberOfMonths:1,showOtherMonths:!0,selectOtherMonths:!0,showButtonPanel:!0,changeYear:!0,onClose:function(a){$("#toN").datepicker("option","minDate",a)}});$("#toN").datepicker({defaultDate:"+1w",changeMonth:!0,numberOfMonths:2,showOtherMonths:!0,selectOtherMonths:!0,showButtonPanel:!0,onClose:function(a){$("#fromN").datepicker("option","maxDate",a)}})});
$(document).ready(function(){$("#checkoutForm #associateLogin").validate({rules:{emailAddress:{required:!0,email:!0},password:{required:!0,password:!0,minlength:8}}})});$(document).ready(function(){$("#submitRequest").submit("click",function(a){confirm("Submit your request?")||($("#updateSrvMessage").html("Associate Services Update Request Cancelled."),fadeInMessage("#updateSrvMessage"),a.preventDefault())})});
function daysLeft(){var a=new Date,b=new Date(a);b.setMonth(0);b.setDate(1);b.setFullYear(b.getFullYear()+1);a=b.getTime()-a.getTime();Math.ceil(a/864E5)}function todaysDate(){var a=new Date,b=a.getMonth()+1,c=a.getDate(),a=a.getFullYear(),b=(10>b?"0"+b:b)+"/"+((10>c?"0"+c:c)+"/");return b+=a}function fadeInOutMessage(a){$(a).fadeIn(100).fadeOut(100).fadeIn(100).fadeOut(2E3)}function fadeInMessage(a){$(a).fadeIn(100).fadeOut(100).fadeIn(100)}
function spinner(a,b,c){b={lines:11,length:14,width:6,radius:12,corners:1,rotate:33,direction:1,color:"#4297d7",speed:1.3,trail:48,shadow:!1,hwaccel:!1,className:"spinner",zIndex:2E9,top:b,left:"auto"};a=document.getElementById(a);var d=(new Spinner(b)).spin(a);$(a).data("spinner",d);setTimeout(function(){d.stop()},c)}var clearTime="-------";
$(document).ready(function(){$("#globalMain").on("click",function(){var a=$(".tableInput:checked").val(),b=$(".gloMT1").val(),c=$(".gloMT2").val(),d=$(".gloAT1").val(),e=$(".gloAT2").val(),f=".sunMT1 .monMT1 .tueMT1 .wedMT1 .thuMT1 .friMT1 .satMT1".split(" "),k=".sunMT2 .monMT2 .tueMT2 .wedMT2 .thuMT2 .friMT2 .satMT2".split(" "),p=".sunAT1 .monAT1 .tueAT1 .wedAT1 .thuAT1 .friAT1 .satAT1".split(" "),s=".sunAT2 .monAT2 .tueAT2 .wedAT2 .thuAT2 .friAT2 .satAT2".split(" "),q="#sun #mon #tue #wed #thu #fri #sat".split(" ");
switch(a){case "everyday":for(a=0;7>a;a++)$(q[a]).each(function(){this.checked=!0}),$(f[a]).val(b),$(k[a]).val(c),$(p[a]).val(d),$(s[a]).val(e);break;case "weekdays":for(a=0;7>a;a++){if(1===a||2===a||3===a||4===a||5===a)$(q[a]).each(function(){this.checked=!0}),$(f[a]).val(b),$(k[a]).val(c),$(p[a]).val(d),$(s[a]).val(e);if(0===a||6===a)$(q[a]).each(function(){this.checked=!1}),$(f[a]).val(clearTime),$(k[a]).val(clearTime),$(p[a]).val(clearTime),$(s[a]).val(clearTime)}break;case "weekends":for(a=0;7>
a;a++){if(1===a||2===a||3===a||4===a||5===a)$(q[a]).each(function(){this.checked=!1}),$(f[a]).val(clearTime),$(k[a]).val(clearTime),$(p[a]).val(clearTime),$(s[a]).val(clearTime);if(0===a||6===a)$(q[a]).each(function(){this.checked=!0}),$(f[a]).val(b),$(k[a]).val(c),$(p[a]).val(d),$(s[a]).val(e)}break;case "tueToSat":for(a=0;7>a;a++){if(2===a||3===a||4===a||5===a||6===a)$(q[a]).each(function(){this.checked=!0}),$(f[a]).val(b),$(k[a]).val(c),$(p[a]).val(d),$(s[a]).val(e);if(0===a||1===a)$(q[a]).each(function(){this.checked=
!1}),$(f[a]).val(clearTime),$(k[a]).val(clearTime),$(p[a]).val(clearTime),$(s[a]).val(clearTime)}}})});
$(document).ready(function(){$(".quickScheduleRequest").submit(function(a){$("#validationQSError").html("");$("#quickScheduleCancel").html("");$("#quickScheduleMessages").html("");var b=$("#quickScheduleMessages"),c=!0,d=$("#datepicker").val(),e=$("#qsStart").val(),f=$("#qsEnd").val(),k=$("#qsFrequency").val(),p=$("#qsLength").val(),s=[],q=validateTime(e,f),h=validateDate(d);$(".quickSchedule:checked").each(function(){s.push($(this).val())});0===$(".quickSchedule:checked").length&&"1 day"!==p&&(b.append("\u2022 <span>(<strong>days</strong>)&nbsp;&nbsp;Select at least one of the <strong>Day</strong> checkboxes from above.</span><br>"),
c=!1);if(""===d||!1===h)b.append("\u2022 <span>(<strong>starting date</strong>)&nbsp;&nbsp;Please enter a valid <strong>starting date</strong>. example:&nbsp;<strong>"+todaysDate()+"</strong>&nbsp;and\n                    <strong>date is today or greater.</strong></span><br>"),$("#datepicker").focus(),c=!1;if(e===clearTime&&f===clearTime||!1===q)b.append("\u2022 <span>(<strong>time in &AMP; time out</strong>)&nbsp;&nbsp;Make sure the selected&nbsp;<strong>time out</strong>\n                        is greater than the selected&nbsp;<strong>time  in</strong>.</span><br>"),
$("#qsStart").focus(),c=!1;e===clearTime&&f!==clearTime&&(b.append("\u2022 <span>(<strong>time in</strong>)&nbsp;&nbsp;Please select a <strong>time in</strong>.</span><br>"),$("#qsStart").focus(),c=!1);e!==clearTime&&f===clearTime&&(b.append("\u2022 <span>(<strong>time out</strong>)&nbsp;&nbsp;Please select a <strong>time out</strong>.</span><br>"),$("#qsEnd").focus(),c=!1);!1===c?($("#validationQSError").html("Please provide valid entries for the following field(s):<br>"),fadeInMessage("#messagesQS"),
a.preventDefault()):(c=new Date(d),a.preventDefault(),confirmMessage("#confirmSchedule",".quickScheduleRequest",b,"#messagesQS","Quick Schedule Request Cancelled.<br>"),a="<tr><td>starting:</td><td>"+formatDate(c)+"</td></tr><tr><td>for:</td><td>"+p+"</td></tr><tr><td>time in:</td><td>"+e+"</td></tr><tr><td>time out:</td><td>"+f+"</td></tr><tr><td>every:</td><td>"+k+" minutes</td></tr><tr><td>day(s):</td><td>"+s.join(", ")+"</td></tr>",$("#confirmSchedule").dialog("open"),$("#confirmSchedule").dialog("option",
"minHeight",250),$("#confirmSchedule .eventHeader").html("Submit request to accept appointments"),$("#confirmSchedule tbody").html(a))})});
$(document).ready(function(){$("#clearSchedule").submit("click",function(a){$("#clearScheduleMessages").html("");$("#validationErrorClr").html("");var b=$("#clearScheduleMessages"),c=$(".schedulerInput:checked").val(),d=$("#datepicker3").val(),e=$("#to").val(),f=$("#from").val(),k=!0;if("undefined"===typeof c)b.append("\u2022 <span>Please select a <strong>Clear Schedule Option</strong>.</span><br>"),k=!1;else switch(c){case "clearDate":""===d?(b.append("\u2022 <span>(<strong>clear date</strong>)&nbsp;&nbsp;Please select a <strong>date to clear</strong>.</span><br>"),
$("#datepicker3").focus(),k=!1):!1===validateDate(d)||!1===valSelectedDate(d)?(b.append("\u2022 <span>(<strong>clear date</strong>)&nbsp;&nbsp;Please select a valid <strong>date to clear</strong>.example:&nbsp;<strong>"+todaysDate()+"</strong>&nbsp;and\n                    <strong>is today's date or greater.</strong></span><br>"),$("#datepicker3").focus(),k=!1):""!==d&&(f=new Date(d),a.preventDefault(),confirmMessage("#confirmSchedule","#clearSchedule",b,"#messagesClear","Clear Schedule Request Cancelled.<br>"),
$("#confirmSchedule").dialog("open"),$("#confirmSchedule").dialog("option","minHeight",170),b="<tr><td>clear date:</td><td>"+formatDate(f)+"</td></tr>",$("#confirmSchedule .eventHeader").html("Clear your appointments on one day"),$("#confirmSchedule tbody").html(b));break;case "clearRange":c="&nbsp;date</strong>.&nbsp;example:&nbsp;<strong>"+todaysDate()+"</strong>&nbsp;and is\n                    <strong>greater than the selected from date.</strong></span><br>";""===e&&""!==f?(b.append("\u2022 <span>(<strong>to date</strong>)&nbsp;&nbsp;Please enter a valid <strong>to date</strong>.</span><br>"),
$("#to").focus(),k=!1):""!==e&&""===f?(b.append("\u2022 <span>(<strong>from date</strong>)&nbsp;&nbsp;Please enter a valid <strong>from date</strong>.</span><br>"),$("#from").focus(),k=!1):""===f&&""===e?(b.append("\u2022 <span>(<strong>from date and to date</strong>)\n            &nbsp;&nbsp;Please select valid <strong>from date and to dates.</strong>.</span><br>"),$("#from").focus(),k=!1):!1===validateDate(e)?(b.append("\u2022 <span>(<strong>clear date range</strong>)&nbsp;&nbsp;Please select a <strong>to"+
c),$("#to").focus(),k=!1):!1===validateDate(f)?(b.append("\u2022 <span>(<strong>clear date range</strong>)&nbsp;&nbsp;Please select a <strong>from"+c),$("#from").focus(),k=!1):!1===validateToFromDates(e,f)?(b.append("\u2022 <span>(<strong>clear date range</strong>)&nbsp;&nbsp;Please select a <strong>from"+c),$("#from").focus(),k=!1):""!==e&&""!==f&&(b=new Date(e),f=new Date(f),a.preventDefault(),confirmMessage("#confirmSchedule","#clearSchedule","#clearScheduleMessages","#messagesClear","Clear Schedule Request Cancelled.<br>"),
$("#confirmSchedule").dialog("open"),b="<tr><td>from: </td><td>"+formatDate(f)+"</td></tr><tr><td>to: </td><td>"+formatDate(b)+"</td></tr>",$("#confirmSchedule .eventHeader").html("Submit request to clear your schedule"),$("#confirmSchedule tbody").html(b));break;case "clearAll":a.preventDefault(),confirmMessage("#confirmSchedule","#clearSchedule","#clearScheduleMessages","#messagesClear","Clear Schedule Request Cancelled.<br>"),$("#confirmSchedule").dialog("open"),$("#confirmSchedule .eventHeader").html("<span style='color: #c00;'>Are you sure you want to Clear your Enitre Schedule?</span>")}!1===
k&&($("#validationErrorClr").html("Please provide valid entries for the following field(s):<br>"),fadeInMessage("#messagesClear"),a.preventDefault())})});
$(document).ready(function(){$(".mainSchedule").submit("click",function(a){$("#validationMSmessages").html("");var b=$("#validationMSmessages"),c=!0,d=[];$(".tableInputMain:checked").each(function(){d.push(this.value)});var e=[];0===d.length&&(b.append("\u2022 <span>(<strong>days</strong>)&nbsp;&nbsp;Select at least one of the <strong>Day</strong> checkboxes from above.</span><br>"),c=!1);if(0!==d){var f=!1,k=$("#fromN").val(),p=$("#toN").val(),s=$("#frequencyN").val(),q;for(q in d){if("sun"===d[q]){var h=
$(".sunMT1").val(),g=$(".sunMT2").val(),m=$(".sunAT1").val(),n=$(".sunAT2").val(),l=!1;h===clearTime||g===clearTime?(b.append("\u2022 ( <strong>Sun morning </strong>)"),b.append(" time in and time out not selected.\n                        &nbsp;Please select&nbsp;<strong>time in</strong> and <strong>time out</strong>.&nbsp; Or uncheck Day checkbox.<br>"),l=!0,c=!1):!1===validateTime(h,g)?(b.append("\u2022 ( <strong>Sun morning </strong>)"),b.append("&nbsp;times not vaild<br>"),l=!0,c=!1,f=!0):h!==
clearTime&&g!==clearTime&&m!==clearTime&&n===clearTime?(b.append("\u2022 ( <strong>Sun afternoon </strong>)"),b.append("<strong> time out</strong> )&nbsp;not vaild&nbsp;\n                        Select a valid time in or reset to '-------'.<br>"),l=!0,c=!1,f=!0):h!==clearTime&&g!==clearTime&&m===clearTime&&n!==clearTime?(b.append("\u2022 ( <strong>Sun afternoon </strong>)"),b.append("<strong> time in</strong> )&nbsp;not vaild&nbsp;\n                        Select a valid time in or reset to '-------'.<br>"),
l=!0,c=!1,f=!0):m===clearTime||n===clearTime||!1!==validateTime(m,n)&&!1!==validateTime(g,m)||(b.append("\u2022 ( <strong>Sun afternoon </strong>)"),b.append("&nbsp;times not vaild<br>"),l=!0,c=!1,f=!0);!0===l&&e.push("sun")}"mon"===d[q]&&(h=$(".monMT1").val(),g=$(".monMT2").val(),m=$(".monAT1").val(),n=$(".monAT2").val(),l=!1,h===clearTime||g===clearTime?(b.append("\u2022 ( <strong>Mon morning </strong>)"),b.append(" time in and time out not selected.\n                        &nbsp;Please select&nbsp;<strong>time in</strong> and <strong>time out</strong>.&nbsp; Or uncheck Day checkbox.<br>"),
l=!0,c=!1):!1===validateTime(h,g)?(b.append("\u2022 ( <strong>Mon morning </strong>)"),b.append("&nbsp;times not vaild<br>"),l=!0,c=!1,f=!0):h!==clearTime&&g!==clearTime&&m!==clearTime&&n===clearTime?(b.append("\u2022 ( <strong>Mon afternoon </strong>)"),b.append("<strong> time out</strong> )&nbsp;not vaild&nbsp;\n                        Select a valid time in or reset to '-------'.<br>"),l=!0,c=!1,f=!0):h!==clearTime&&g!==clearTime&&m===clearTime&&n!==clearTime?(b.append("\u2022 ( <strong>Mon afternoon </strong>)"),
b.append("<strong> time in</strong> )&nbsp;not vaild&nbsp;\n                        Select a valid time in or reset to '-------'.<br>"),l=!0,c=!1,f=!0):m===clearTime||n===clearTime||!1!==validateTime(m,n)&&!1!==validateTime(g,m)||(b.append("\u2022 ( <strong>Mon afternoon </strong>)"),b.append("&nbsp;times not vaild<br>"),l=!0,c=!1,f=!0),!0===l&&e.push("mon"));"tue"===d[q]&&(h=$(".tueMT1").val(),g=$(".tueMT2").val(),m=$(".tueAT1").val(),n=$(".tueAT2").val(),l=!1,h===clearTime||g===clearTime?(b.append("\u2022 ( <strong>Tue morning </strong>)"),
b.append(" time in and time out not selected.\n                        &nbsp;Please select&nbsp;<strong>time in</strong> and <strong>time out</strong>.&nbsp; Or uncheck Day checkbox.<br>"),l=!0,c=!1):!1===validateTime(h,g)?(b.append("\u2022 ( <strong>Tue morning </strong>)"),b.append("&nbsp;times not vaild<br>"),l=!0,c=!1,f=!0):h!==clearTime&&g!==clearTime&&m!==clearTime&&n===clearTime?(b.append("\u2022 ( <strong>Tue afternoon </strong>)"),b.append("<strong> time out</strong> )&nbsp;not vaild&nbsp;\n                        Select a valid time in or reset to '-------'.<br>"),
l=!0,c=!1,f=!0):h!==clearTime&&g!==clearTime&&m===clearTime&&n!==clearTime?(b.append("\u2022 ( <strong>Tue afternoon </strong>)"),b.append("<strong> time in</strong> )&nbsp;not vaild&nbsp;\n                        Select a valid time in or reset to '-------'.<br>"),l=!0,c=!1,f=!0):m===clearTime||n===clearTime||!1!==validateTime(m,n)&&!1!==validateTime(g,m)||(b.append("\u2022 ( <strong>Tue afternoon </strong>)"),b.append("&nbsp;times not vaild<br>"),l=!0,c=!1,f=!0),!0===l&&e.push("tue"));if("wed"===
d[q]){var h=$(".wedMT1").val(),g=$(".wedMT2").val(),m=$(".wedAT1").val(),n=$(".wedAT2").val(),l=!1,u="\u2022 ( <strong>Wed afternoon </strong>)";h===clearTime||g===clearTime?(b.append("\u2022 ( <strong>Wed morning </strong>)"),b.append(" time in and time out not selected.\n                        &nbsp;Please select&nbsp;<strong>time in</strong> and <strong>time out</strong>.&nbsp; Or uncheck Day checkbox.<br>"),l=!0,c=!1):!1===validateTime(h,g)?(b.append("\u2022 ( <strong>Wed morning </strong>)"),
b.append("&nbsp;times not vaild<br>"),l=!0,c=!1,f=!0):h!==clearTime&&g!==clearTime&&m!==clearTime&&n===clearTime?(b.append(u),b.append("<strong> time out</strong> )&nbsp;not vaild&nbsp;\n                        Select a valid time in or reset to '-------'.<br>"),l=!0,c=!1,f=!0):h!==clearTime&&g!==clearTime&&m===clearTime&&n!==clearTime?(b.append(u),b.append("<strong> time in</strong> )&nbsp;not vaild&nbsp;\n                        Select a valid time in or reset to '-------'.<br>"),l=!0,c=!1,f=!0):
m===clearTime||n===clearTime||!1!==validateTime(m,n)&&!1!==validateTime(g,m)||(b.append(u),b.append("&nbsp;times not vaild<br>"),l=!0,c=!1,f=!0);!0===l&&e.push("wed")}"thu"===d[q]&&(h=$(".thuMT1").val(),g=$(".thuMT2").val(),m=$(".thuAT1").val(),n=$(".thuAT2").val(),l=!1,h===clearTime||g===clearTime?(b.append("\u2022 ( <strong>Thu morning </strong>)"),b.append(" time in and time out not selected.\n                        &nbsp;Please select&nbsp;<strong>time in</strong> and <strong>time out</strong>.&nbsp; Or uncheck Day checkbox.<br>"),
l=!0,c=!1):!1===validateTime(h,g)?(b.append("\u2022 ( <strong>Thu morning </strong>)"),b.append("&nbsp;times not vaild<br>"),l=!0,c=!1,f=!0):h!==clearTime&&g!==clearTime&&m!==clearTime&&n===clearTime?(b.append("\u2022 ( <strong>Thu afternoon </strong>)"),b.append("<strong> time out</strong> )&nbsp;not vaild&nbsp;\n                        Select a valid time in or reset to '-------'.<br>"),l=!0,c=!1,f=!0):h!==clearTime&&g!==clearTime&&m===clearTime&&n!==clearTime?(b.append(u),b.append("<strong> time in</strong> )&nbsp;not vaild&nbsp;\n                        Select a valid time in or reset to '-------'.<br>"),
l=!0,c=!1,f=!0):m===clearTime||n===clearTime||!1!==validateTime(m,n)&&!1!==validateTime(g,m)||(b.append("\u2022 ( <strong>Thu afternoon </strong>)"),b.append("&nbsp;times not vaild<br>"),l=!0,c=!1,f=!0),!0===l&&e.push("thu"));"fri"===d[q]&&(h=$(".friMT1").val(),g=$(".friMT2").val(),m=$(".friAT1").val(),n=$(".friAT2").val(),l=!1,h===clearTime||g===clearTime?(b.append("\u2022 ( <strong>Fri morning </strong>)"),b.append(" time in and time out not selected.\n                        &nbsp;Please select&nbsp;<strong>time in</strong> and <strong>time out</strong>.&nbsp; Or uncheck Day checkbox.<br>"),
l=!0,c=!1):!1===validateTime(h,g)?(b.append("\u2022 ( <strong>Fri morning </strong>)"),b.append("&nbsp;times not vaild<br>"),l=!0,c=!1,f=!0):h!==clearTime&&g!==clearTime&&m!==clearTime&&n===clearTime?(b.append("\u2022 ( <strong>Fri afternoon </strong>)"),b.append("<strong> time out</strong> )&nbsp;not vaild&nbsp;\n                        Select a valid time in or reset to '-------'.<br>"),l=!0,c=!1,f=!0):h!==clearTime&&g!==clearTime&&m===clearTime&&n!==clearTime?(b.append("\u2022 ( <strong>Fri afternoon </strong>)"),
b.append("<strong> time in</strong> )&nbsp;not vaild&nbsp;\n                        Select a valid time in or reset to '-------'.<br>"),l=!0,c=!1,f=!0):m===clearTime||n===clearTime||!1!==validateTime(m,n)&&!1!==validateTime(g,m)||(b.append("\u2022 ( <strong>Fri afternoon </strong>)"),b.append("&nbsp;times not vaild<br>"),l=!0,c=!1,f=!0),!0===l&&e.push("fri"));if("sat"===d[q]){var h=$(".satMT1").val(),g=$(".satMT2").val(),m=$(".satAT1").val(),n=$(".satAT2").val(),t=!1;h===clearTime||g===clearTime?
(b.append("\u2022 ( <strong>Sat morning </strong>)"),b.append(" time in and time out not selected.\n                        &nbsp;Please select&nbsp;<strong>time in</strong> and <strong>time out</strong>.&nbsp; Or uncheck Day checkbox.<br>"),t=!0,c=!1):!1===validateTime(h,g)?(b.append("\u2022 ( <strong>Sat morning </strong>)"),b.append("&nbsp;times not vaild<br>"),t=!0,c=!1,f=!0):h!==clearTime&&g!==clearTime&&m!==clearTime&&n===clearTime?(b.append("\u2022 ( <strong>Sat afternoon </strong>)"),b.append("<strong> time out</strong> )&nbsp;not vaild&nbsp;\n                        Select a valid time in or reset to '-------'.<br>"),
t=!0,c=!1,f=!0):h!==clearTime&&g!==clearTime&&m===clearTime&&n!==clearTime?(b.append("\u2022 ( <strong>Sat afternoon </strong>)"),b.append("<strong> time in</strong> )&nbsp;not vaild&nbsp;\n                        Select a valid time in or reset to '-------'.<br>"),t=!0,c=!1,f=!0):m===clearTime||n===clearTime||!1!==validateTime(m,n)&&!1!==validateTime(g,m)||(b.append("\u2022 ( <strong>Sat afternoon </strong>)"),b.append("&nbsp;times not vaild<br>"),t=!0,c=!1,f=!0)}!0===t&&e.push("sat")}if(""===k&&
""===p)b.append("<span>\u2022 (<strong>date from & date to</strong>)&nbsp;&nbsp;Please enter valid&nbsp;<strong>date from</strong> and<strong> to dates</strong>.</span><br>"),c=!1,$("#fromN").focus();else if(""===k)b.append("<span>\u2022 (<strong>date from</strong>)&nbsp;&nbsp;Please enter valid&nbsp;<strong>date from</strong>.</span><br>"),c=!1,$("#fromN").focus();else if(""!==k&&""===p)b.append("<span>\u2022 (<strong>date to</strong>)&nbsp;&nbsp;Please enter valid&nbsp;<strong>date to</strong>.</span><br>"),
c=!1,$("#toN").focus();else if(""!==k||""!==p)!1===validateToFromDates(p,k)?(b.append("<span>\u2022 (<strong>date from & date to</strong>)&nbsp;&nbsp;Please enter valid&nbsp;<strong>date from</strong> and <strong>to dates</strong>. example:&nbsp;<strong>"+todaysDate()+"</strong>&nbsp;and\n                    <strong>date is today or greater.</strong></span><br>"),$("#fromN").focus(),c=!1):!1===validateDate(k)?(b.append("<span>\u2022 (<strong>date from</strong>)&nbsp;&nbsp;Please enter valid&nbsp;<strong>date from</strong>.</span><br>"),
$("#fromN").focus(),c=!1):!1===validateDate(p)&&(b.append("<span>\u2022 (<strong>date to</strong>)&nbsp;&nbsp;Please enter valid&nbsp;<strong>date to</strong>.</span><br>"),$("#toN").focus(),c=!1)}!0===f?b.append("<span>\u2022 (<strong>time in &AMP; time out</strong>)&nbsp;&nbsp;Please check these selected Day(s)&nbsp;<strong>"+capitalize(e.join(", "))+"</strong> &nbsp;-&nbsp;Make sure the selected&nbsp;<strong>time out&nbsp;</strong>is greater than the selected&nbsp;<strong>time  in</strong>.</span><br>"):
$("#dayTimeError").html("");!1===c?($("#validationMSError").html("Please provide valid entries for the following field(s):<br>"),fadeInMessage("#messagesMain"),a.preventDefault()):($("#validationMSError").html(""),b=new Date(p),k=new Date(k),c="",a.preventDefault(),1<d.length&&(c="s"),confirmMessage("#confirmSchedule",".mainSchedule","#validationMSmessages","#messagesMain","Main Schedule Request Cancelled.<br>"),a="<tr><td>from:</td><td>"+formatDate(k)+"</td></tr><tr><td>to:</td><td>"+formatDate(b)+
"</td></tr><tr><td>every:</td><td>"+s+" minutes</td></tr><tr><td>day"+c+":</td><td>"+d.join(", ")+"</td></tr>",$("#confirmSchedule").dialog("open"),$("#confirmSchedule").dialog("option","minHeight",180),$("#confirmSchedule .eventHeader").html("Submit request to accept appointments."),$("#confirmSchedule tbody").html(a))})});function capitalize(a){return a.toUpperCase()}
function validateDate(a){var b=!0,c=new Date,d=a.substring(0,2),e=a.substring(3,5),f=a.substring(6,10),d=new Date(f,d-1,e,23,59);if(!/^[01]?\d\/[0-3]\d\/\d{4}$/.test(a)||d<c)b=!1;return b}function valSelectedDate(a,b){var c=!0,d=new Date,e=d.getHours(),f=d.getMinutes(),k=d.getSeconds(),p=a.substring(0,2),s=a.substring(3,5),q=a.substring(6,10),e=new Date(q,p-1,s,e,f,k+1);b instanceof Date?b<d&&(c=!1):e<d&&(c=!1);return c}
function validateToFromDates(a,b){var c=!0,d=b.substring(0,2),e=b.substring(3,5),f=b.substring(6,10),k=new Date(f,d-1,e),d=a.substring(0,2),e=a.substring(3,5),f=a.substring(6,10),d=new Date(f,d-1,e);if(!validateDate(b)||!validateDate(a)||k>d||!valSelectedDate(b))c=!1;return c}
function validateTime(a,b){var c=a.search("PM"),d=b.search("PM"),e=a.split(":",1),f=b.split(":",1),k=e[0],p=f[0],f=a.search("30"),s=b.search("30"),e=!0,k=Number(k),p=Number(p);-1!==c&&12!==k&&(k+=12);-1!==d&&12!==p&&(p+=12);c=new Date(2013,1,1,p,-1!==s?30:0);(new Date(2013,1,1,k,-1!==f?30:0)).getTime()>=c.getTime()&&(e=!1);return e}
$(document).ready(function(){$("#newEvent").hide();$("#delete").hide();$(".calEvent").hide();$("#errorMsg").hide();var a=$("#errorMsg"),b;$("#calendar").fullCalendar({header:{left:"prev,today,next",center:"title",right:"month,agendaWeek,agendaDay"},dragOpacity:{month:.2,"":.5},slotMinutes:15,selectable:!0,selectHelper:!0,dayClick:function(){$(this).css("background-color","dfeffc")},eventClick:function(a,b){evtClick(a,b)},select:function(a,b,e){newEvent(a,b,e)},editable:!0,eventDrop:function(c,d){c.action=
"add";var e=eventConflictCk(c.start,c.end,c.id);0<e.length?(openMsg(c.start,c.end,c.allDay,c,d),a.dialog("open"),a.dialog("option","minWidth",350),a.dialog("option","maxWidth",600),b=1===e.length?"<u>overlaps with another appointment</u>":"<u>overlaps with mulitple appointments</u>",$("#errorMsg div").html("<normal style='color: #c00;'>Scheduling Conflict!</normal><br><br> Moving client:<strong>"+c.firstName+"</strong> scheduled service:<strong>"+stripName(c.title)+"</strong><br>"+b),$("#errorTable2 tbody").html("<tr><th title='client first name'>client</th><th title='appointment ID number'>event&#35;</th><th title='service to perform'>service<th title='service start time'>start</th><th title='service end time'>end</th><th title='current appointment status'>status</th></tr>"),
$("#errorTable2 tbody").append("<tr><td>"+c.firstName+"</td><td>"+c.eventId+"</td><td>"+stripName(c.title)+"</td><td>"+fmtTimeAlt(c.start)+"</td><td>"+fmtTimeAlt(c.end)+'</td><td style="color:'+c.serviceStatus.statusColor+'">'+c.serviceStatus.statusName+"</td></tr>"),$(".errorTable tbody").html("<tr><th title='client first name'>client</th><th title='appointment ID number'>event&#35;</th><th title='service to perform'>service<th title='service start time'>start</th><th title='service end time'>end</th><th title='current appointment status'>status</th><th title='check to cancel appointment'>cancel</th></tr>"),
$.each(e,function(a,b){$(".errorTable tbody").append("<tr><td>"+b.firstName+"</td><td>"+b.eventId+"</td><td>"+stripName(b.title)+"</td><td>"+fmtTimeAlt(b.start)+"</td><td>"+fmtTimeAlt(b.end)+'</td><td style="color:'+b.serviceStatus.statusColor+'">'+b.serviceStatus.statusName+'</td><td><input type="checkbox" id="cancel" value="'+b.eventId+'"></td></tr>')})):postToServer(c)},eventResize:function(c,d){c.serviceTime=calculateSvcTime(c.start,c.end);c.action="add";var e=eventConflictCk(c.start,c.end,c.id);
0<e.length?(openMsg(c.start,c.end,c.allDay,c,d),a.dialog("open"),a.dialog("option","minWidth",350),a.dialog("option","maxWidth",600),b=1===e.length?"<u>overlaps with another appointment</u>":"<u>overlaps with mulitple appointments</u>",$("#errorMsg div").html("<normal style='color: #c00;'>Scheduling Conflict!</normal><br><br> Changing time for client:<strong>"+c.firstName+"</strong> scheduled service:<strong>"+stripName(c.title)+"</strong><br>"+b),$("#errorTable2 tbody").html("<tr><th title='client first name'>client</th><th title='appointment ID number'>event&#35;</th><th title='service to perform'>service<th title='service start time'>start</th><th title='service end time'>end</th><th title='current appointment status'>status</th></tr>"),
$("#errorTable2 tbody").append("<tr><td>"+c.firstName+"</td><td>"+c.eventId+"</td><td>"+stripName(c.title)+"</td><td>"+fmtTimeAlt(c.start)+"</td><td>"+fmtTimeAlt(c.end)+'</td><td style="color:'+c.serviceStatus.statusColor+'">'+c.serviceStatus.statusName+"</td></tr>"),$(".errorTable tbody").html("<tr><th title='client first name'>client</th><th title='appointment ID number'>event&#35;</th><th title='service to perform'>service<th title='service start time'>start</th><th title='service end time'>end</th><th title='current appointment status'>status</th><th title='check to cancel appointment'>cancel</th></tr>"),
$.each(e,function(a,b){$(".errorTable tbody").append("<tr><td>"+b.firstName+"</td><td>"+b.eventId+"</td><td>"+stripName(b.title)+"</td><td>"+fmtTimeAlt(b.start)+"</td><td>"+fmtTimeAlt(b.end)+'</td><td style="color:'+b.serviceStatus.statusColor+'">'+b.serviceStatus.statusName+'</td><td><input type="checkbox" id="cancel" value="'+b.eventId+'"></td></tr>')})):postToServer(c)},eventSources:[{url:"../FullCalendar",type:"GET",dataType:"json",data:{title:"title",start:"start",end:"end"},error:function(){$("#postDataError").html("There was an error while fetching calendar events!<br>Click Calendar on the sidebar or refresh the page to re-fetch calendar events.<br>Contact support if problem persists.")}}]})});
function postToServer(a){var b=[],c={};c.title=stripName(a.title);c.start=a.start;c.end=a.end;c.serviceTime=a.serviceTime;c.allDay=a.allDay;c.backgroundColor=a.backgroundColor;c.eventId=a.eventId;c.serviceId=a.serviceId;c.firstName=a.firstName;c.lastName=a.lastName;c.emailAddress=a.emailAddress;c.serviceId=a.serviceId;c.associateId=a.associateId;c.associateName=a.associateName;c.customerId=a.customerId;c.mobilePhone=a.mobilePhone;c.action=a.action;c.notifyClient=a.notifyClient;c.restoreTime=a.restoreTime;
c.newClient=a.newClient;c.statusId=a.statusId;c.cancelEvts=a.cancelEvts;b.push(c);b=JSON.stringify(b);b=b.replace(/\"/g,"'");1234===a.eventId||"updateStatus"===a.action||!0===a.cancelEvts instanceof Object?postEvents(b,a):postEvents(b)}function confirmDialog(a){$("<div>"+a.firstName+"</div>");$("#dialog").dialog("open")}
function postEvents(a,b){$("#postDataError").html("");$.ajax({type:"post",url:"../FullCalPost",data:{calEvents:a},error:function(a,b,e){$("#postDataError").append("Error Posting Data: "+a.status+" - "+e)},success:function(){"undefined"!==typeof b&&(1234===b.eventId&&$("#calendar").fullCalendar("removeEvents",b.id),$("#calendar").fullCalendar("refetchEvents"))}})}
function formatDate(a){var b=$.fullCalendar.formatDate(a,"ddd"),c=$.fullCalendar.formatDate(a,"MMM"),d=$.fullCalendar.formatDate(a,"dd");a=$.fullCalendar.formatDate(a,"yyyy");return b+" "+c+" "+d+", "+a}function formatDateNew(a){var b=$.fullCalendar.formatDate(a,"MM"),c=$.fullCalendar.formatDate(a,"dd");a=$.fullCalendar.formatDate(a,"yyyy");return b+"/"+c+"/"+a}function formatTime(a){return $.fullCalendar.formatDate(a,"h:mm TT")}function fmtTimeAlt(a){return $.fullCalendar.formatDate(a,"h:mmt")}
function formatPhone(a){a=a.replace(/[^0-9]/g,"");return a=a.replace(/(\d{3})(\d{3})(\d{4})/,"$1-$2-$3")}function addMinutes(a,b){return new Date(a.getTime()+6E4*b)}function calculateSvcTime(a,b){return(b.getTime()-a.getTime())/1E3/60}$(function(){$("#refreshCalendar").click(function(){$("#calendar").fullCalendar("refetchEvents");$("#postDataSuccess").html("Calendar Refresh Successful!");fadeInOutMessage("#messages")})});
$(function(){$("#updateCalendar").click(function(){var a=[],b=$("#calendar").fullCalendar("clientEvents");$.each(b,function(b,d){var e={};e.title=stripName(d.title);e.start=d.start;e.end=d.end;e.serviceTime=d.serviceTime;e.allDay=d.allDay;e.backgroundColor=d.backgroundColor;e.color=d.color;e.editable=d.editable;e.durationEditable=d.durationEditable;e.textColor=d.textColor;e.eventId=d.eventId;e.serviceId=d.serviceId;e.firstName=d.firstName;e.lastName=d.lastName;e.emailAddress=d.emailAddress;e.associateName=
d.associateName;e.customerId=d.customerId;e.associateId=d.associateId;e.statusId=d.statusId;e.action="add";a.push(e)});b=JSON.stringify(a);b=b.replace(/\"/g,"'");postEvents(b)})});
function confirmMessage(a,b,c,d,e){$(a).dialog({autoOpen:!1,modal:!0,width:"auto",height:"auto",maxWidth:600,show:{duration:200},hide:{duration:200},buttons:{Submit:function(){$(b).unbind("submit").submit();$(this).dialog("close")},Cancel:function(){$(this).dialog("close");$(c).html(e);fadeInMessage(d)}}});$("#confirmSchedule tbody").html("")}
function eventConflictCk(a,b,c){var d=[],e=a.getTime(),f=b.getTime(),k,p=stripTime(a);a=$("#calendar").fullCalendar("clientEvents");$.each(a,function(a,b){k=stripTime(b.start);if(!b.allDay&&k.getTime()===p.getTime()&&b.id!==c&&"Confirmed"===b.serviceStatus.statusName||"Pending"===b.serviceStatus.statusName){var h=b.start.getTime(),g=b.end.getTime();e<h&&e<g&&f>h&&f<g&&d.push(b);e<g&&e>h&&f>g&&f>g&&d.push(b);e>h&&e<g&&f>h&&f<g&&d.push(b);e<h&&e<g&&f>h&&f>g&&d.push(b);e!==h&&f!==g||d.push(b)}});return d}
function stripTime(a){var b=a.getFullYear(),c=a.getMonth();a=a.getDate();var d=new Date;d.setFullYear(b);d.setMonth(c);d.setDate(a);d.setHours(0);d.setMinutes(0);d.setSeconds(0);d.setMilliseconds(0);return d}
function newEvent(a,b,c){var d=$("#pastDateMsg"),e=new Date,f=stripTime(e),k=stripTime(a);c&&k<f?(openPastMsg(a,b,c),d.dialog("open"),d.dialog("option","minWidth",250),$("#pastDateMsg span").addClass("ui-icon ui-icon-alert"),$("#pastDateMsg figcaption").html("Past Date Selection!"),$("#pastDateMsg tfoot").html("The Date you selected for creating <br>a new Event <b>"+formatDate(a)+"</b> is a Date in the past.")):!c&&a.getTime()<e.getTime()?(openPastMsg(a,b,c),d.dialog("open"),d.dialog("option","minWidth",
250),$("#pastDateMsg span").addClass("ui-icon ui-icon-alert"),$("#pastDateMsg figcaption").html("Past Date &#38; Time Selection!"),$("#pastTable tbody").html("<tr><td>date:</td><td>"+formatDate(a)+"</td></tr><tr><td>time:</td><td>"+formatTime(a)+"</td></tr>"),$("#pastTable tfoot").html("<tr><th colspan='2'> is a Date &#38; Time that is in the past.</th></tr>")):newEvt(a,b,c)}
function newEvt(a,b,c){createEvent(a,b,c);$("#newEvent").dialog("open");$("#firstNm").autocomplete({source:function(a,b){$.ajax({url:"../autocomplete",dataType:"json",data:{term:a.term},success:function(a){b($.map(a,function(a){return{label:a.firstName+" "+a.lastName+" "+a.email,value:a.firstName,lastName:a.lastName,email:a.email,company:a.company,id:a.id,associateName:a.preferredAssociateName,preferredAssociateId:a.preferredAssociateId,mobilePhone:a.mobilePhone}}))}})},minLength:2,select:function(a,
b){$("#customerId").val(b.item.id);$("#firstNm").val(b.item.firstName);$("#lastNm").val(b.item.lastName);$("#email").val(b.item.email);$("#company").val(b.item.company);$("#clientid").val(b.item.id);$("#associateName").val(b.item.associateName);$("#associateId").val(b.item.preferredAssociateId);"undefined"!==typeof b.item.mobilePhone&&$("#mobilePhone").val(formatPhone(b.item.mobilePhone))}});$("#associateName").autocomplete({source:function(a,b){$.ajax({url:"../associateAutoComp",dataType:"json",
data:{term:a.term},success:function(a){b($.map(a,function(a){return{label:a.firstName+" "+a.lastName,value:a.firstName,lastName:a.lastName,email:a.email,mobilePhone:a.mobilePhone,id:a.id}}))}})},minLength:2,select:function(a,b){$("#associateName").val(b.item.firstName);$("#associatelastName").val(b.item.lastName);$("#associateId").val(b.item.id);$("#associateEmail").val(b.item.email);$("#associateMobilePhone").val(b.item.mobilePhone)}});$("calendar").fullCalendar("unselect")}
function createEvent(a,b,c){function d(a){w.html(a).addClass("ui-state-highlight");setTimeout(function(){w.removeClass("ui-state-highlight",1500)},500)}function e(a,b,c,e){return a.val().length>e||a.val().length<c?(a.addClass("ui-state-error"),d("Length of "+b+" must be between "+c+" and "+e+" characters"),!1):!0}function f(a,b,c){if(b.test(a.val()))return!0;a.addClass("ui-state-error");d(c);return!1}function k(){var a=$("#servicetitle").val(),b=a.lastIndexOf(":");b++;return a.substring(b)}$(".validateTips").html("Complete Service Fields");
var p=$("#customerId"),s=$("#servicetitle"),q=$("#firstNm"),h=$("#lastNm"),g=$("#service"),m=$("#status"),n=$("#email"),l=$("#associateName"),u=$("#mobilePhone"),t=$("#backgroundColor"),z=$("#associateId"),D=$("#associateEmail"),E=$("#associateMobilePhone"),F=$("#associatelastName"),x=$("#newEventTable .newClient:checked"),y=$("#newEventTable .notifyClient:checked"),G=$(".eventHeader"),B=$("#endTime"),H=$("#startTime"),w=$(".validateTips"),C=$([]).add(q).add(h).add(n.add(l).add(t).add(g).add(p).add(u).add(z).add(D).add(E).add(F));
s.change(function(){var b=k(),b=addMinutes(a,b);B.val(formatTime(b))});G.html("<strong>"+formatDate(a)+"</strong>");c?$("#startend").hide():($("#startend").show(),g=b,g=k(),g=addMinutes(a,g),B.val(formatTime(g)),H.val(formatTime(a)));$("#newEvent").dialog({autoOpen:!1,width:"auto",modal:!0,maxWidth:600,minWidth:325,show:{duration:200},hide:{duration:200},buttons:{"Create Event":function(){var g=!0;C.removeClass("ui-state-error");g=(g=(g=(g=(g=(g=(g=(g=(g=g&&e(q,"First Name",3,45))&&e(h,"Last Name",
3,45))&&e(s,"Service",3,30))&&e(l,"Associate Name",3,45))&&e(n,"Email",6,80))&&f(q,/^[a-z]([0-9a-z _])+$/i,"First Name may consist of a-z, 0-9, underscores, begin with a letter."))&&f(h,/^[a-z]([0-9a-z _])+$/i,"Last Name may consist of a-z, 0-9, underscores, begin with a letter."))&&f(n,/^((([a-z]|\d|[!#\$%&'\*\+\-\/=\?\^_`{\|}~]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])+(\.([a-z]|\d|[!#\$%&'\*\+\-\/=\?\^_`{\|}~]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])+)*)|((\x22)((((\x20|\x09)*(\x0d\x0a))?(\x20|\x09)+)?(([\x01-\x08\x0b\x0c\x0e-\x1f\x7f]|\x21|[\x23-\x5b]|[\x5d-\x7e]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(\\([\x01-\x09\x0b\x0c\x0d-\x7f]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF]))))*(((\x20|\x09)*(\x0d\x0a))?(\x20|\x09)+)?(\x22)))@((([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])*([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])))\.)+(([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])*([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])))\.?$/i,
"eg. jdoe@doe.com"))&&f(u,/^\d{3}-\d{3}-\d{4}/,"Mobile Phone format 999-999-9999");if(!c){var v=b,v=k(),v=addMinutes(a,v);0<eventConflictCk(a,v).length&&(d("<normal style='color: #c00;'> Appointment Overlap!</normal><br>Selected time &#38; service overlaps with an existing appointment."),g=!1)}if(g){var r=s.val(),A=r.indexOf(":",0),g=r.substring(0,A);A++;var w=r.indexOf(":",A);w++;v=k();w--;s=r.substring(w,A);b=addMinutes(a,v);p=p.val();""===p&&(p=0);q=q.val();h=h.val();n=n.val();l=l.val();z=z.val();
t=t.val();u=u.val();m=m.val();y=y.val();x=x.val();y="true"===y?!0:!1;x="true"===x?!0:!1;$("#calendar").fullCalendar("renderEvent",{title:s,start:a,end:b,allDay:c,backgroundColor:t,color:null,editable:!0,durationEditable:!0,textColor:null,eventId:1234,serviceId:g,serviceTime:v,firstName:q,lastName:h,emailAddress:n,mobilePhone:u,associateName:l,associateId:z,customerId:p,statusId:m,notifyClient:y,newClient:x},!0);r={};r.title=s;r.start=a;r.end=b;r.allDay=c;r.backgroundColor=t;r.eventId=1234;r.serviceId=
g;r.serviceTime=v;r.firstName=q;r.lastName=h;r.emailAddress=n;r.mobilePhone=u;r.associateId=z;r.associateName=l;r.customerId=p;r.statusId=m;r.notifyClient=y;r.newClient=x;r.action="add";postToServer(r);$("#calendar").fullCalendar("unselect");$(this).dialog("close")}},Cancel:function(){$(this).dialog("close")}},close:function(){C.val("").removeClass("ui-state-error");w.html("")}})}
function openMsg(a,b,c,d,e){$(function(){$("#errorMsg").dialog({autoOpen:!1,modal:!0,width:"auto",height:"auto",buttons:{Cancel:function(){d instanceof Object&&$("#calendar").fullCalendar("refetchEvents");$(this).dialog("close")},Allow:function(){if(void 0===typeof e)newEvt(a,b,c);else{var f=[];$("#cancel:checked").each(function(){f.push(this.value)});0<f.length&&(d.cancelEvts=f);postToServer(d)}$(this).dialog("close")}},close:function(){$("#errorMsg tbody").html("")}})})}
function openPastMsg(a,b,c){$(function(){$("#pastDateMsg").dialog({autoOpen:!1,modal:!0,width:"auto",maxWidth:400,buttons:{Cancel:function(){$(this).dialog("close")},Allow:function(){newEvt(a,b,c);$(this).dialog("close")}},close:function(){$("#pastTable tbody").html("");$("#pastDateMsg figcaption").html("");$("#pastTable tfoot").html("")}})})}
function evtClick(a,b){var c="No",d=$(".calEvent");!0===a.allDay&&(c="Yes");var e=0;!0===a.associate2.imgUpl&&(e=a.associate2.id);var f=0;!0===a.client.imgUpl&&(f=a.customerId);c="<tr><td title='client first and last name'>client:</td><td>"+a.firstName+" "+a.lastName+'  <img src="../img/clients/'+f+'.png" alt="client img" alt="img"></td></tr><tr><td title=\'client email address\'>email:</td><td><a href=\'mailto:'+a.emailAddress+" '>"+a.emailAddress+"</a></td></tr><tr><td title='mobile phone'>mobile:</td><td>"+
a.client.mobilePhone+"</td></tr><tr><td title='service to perform'>service:</td><td>"+stripName(a.title)+"</td></tr><tr><td title='date of service'>date:</td><td>"+formatDate(a.start)+"</td></tr><tr><td title='service start time'>start:</td><td>"+formatTime(a.start)+"</td></tr><tr><td title='service end time'>end:</td><td>"+formatTime(a.end)+"</td></tr><tr><td title='event id number'>event:</td><td>"+a.eventId+"</td></tr><tr><td title='estimated time of service'>eta:</td><td>"+minutesFormat(a.serviceTime)+
"</td></tr><tr><td title='is event scheduled all day'>all day:</td><td>"+c+"</td></tr><tr><td title='associate first name'>associate:</td><td>"+a.associate2.firstName+'  <img src="../img/associates/'+e+'.png" alt="associate img" alt="img"></td></tr><tr><td>status:</td><td style="color:'+a.serviceStatus.statusColor+'">'+a.serviceStatus.statusName+"</td></tr>";openEvent(a,c,b);d.dialog("option","title","Appointment Info");d.dialog("open");d.dialog("option","minHeight",380);$(".calEvent .eventInfoTable").html(c);
$(this).css("border-color","#c00")}
function openEvent(a,b){var c=$("#updateStatus"),d=a.serviceStatus.statusId;$(".calEvent").dialog({autoOpen:!1,width:"auto",hegith:"auto",maxWidth:600,minWidth:250,modal:!0,show:{duration:200},hide:{duration:200},buttons:{OK:function(){c=c.val();d!==parseInt(c)&&(a.statusId=c,a.action="updateStatus",postToServer(a));$(this).dialog("close")},Delete:function(){removeEvent(a);$("#delete").dialog("open");$("#delete .eventHeader").html("<span style='color: #c00;'>Are you sure you want<br>to <strong>DELETE</strong> this appointment?</span>");$("#delete .eventInfoTable").html(b);
$(this).dialog("close")}}})}function removeEvent(a){$("#delete").dialog({autoOpen:!1,width:"auto",hegith:"auto",maxWidth:600,minWidth:300,modal:!0,show:{duration:200},hide:{duration:200},buttons:{No:function(){$(this).dialog("close")},Yes:function(){a.restoreTime=$("#notifyCancelTabel .restoreTime:checked").val();a.notifyClient=$("#notifyCancelTabel .notifyClient:checked").val();$("#calendar").fullCalendar("removeEvents",a._id);$(this).dialog("close");a.action="delete";postToServer(a)}}})}
function minutesFormat(a){var b=a%60;a=Math.floor(a/60);var c=" hour ",b=(10>b?"0":"")+b;if(0===a)return b+" minutes";1<a&&(c=" hours ");return"00"===b?a+c:a+c+b+" minutes"}function stripName(a){var b=a.indexOf(":",0);-1!==b&&(a=a.substring(0,b));return a}$(function(){setInterval("rotateImages()",3E3)});
function rotateImages(){var a=$("#photoShow div.current"),b=a.next();0===b.length&&(b=$("#photoShow div:first"));a.removeClass("current").addClass("previous");b.css({opacity:0}).addClass("current").animate({opacity:1},1E3,function(){a.removeClass("previous")})}$(document).ready(function(){$("h3").hover(function(){$(this).animate({backgroundColor:"#99CCFF",borderRadius:"5px"})},function(){$(this).animate({backgroundColor:"none"})})});